# Generated by Django 4.0.2 on 2022-05-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
